//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrDuck {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class MrDuckSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MrDuckSettings defaultInstance = ((MrDuckSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MrDuckSettings())));
        
        public static MrDuckSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMrDuckMute {
            get {
                return ((bool)(this["IsMrDuckMute"]));
            }
            set {
                this["IsMrDuckMute"] = value;
            }
        }
    }
}
